### ISSUE TITLE
ossec 2.8 breaks analogi

### ISSUE THREAD

**Issue by shadyb** [ECSC/analogi#16]
Hi,

Not sure if you are aware of this but OSSEC 2.8 breaks analogi. They have drop the data table and merged its fields into the alert table. No data sources have been dropped, they have only been reshuffled, so its just a matter of updating queries.

**Comment by prudnitskiy** [comment]
There is NO table "data" in OSSEC 2.8 (I can send you a schema, if you need it), so Analogi will not work with the brand-new ossec.
