### ISSUE TITLE
issues show in detail.php while connecting with ossec 2.8.3

### ISSUE THREAD

**Issue by thinksabin** [ECSC/analogi#17]
I got this error while using analogi with ossec 2.8.3 . how to fix this issue?
![ossec-analogy-error](https://cloud.githubusercontent.com/assets/6102027/11057376/875dd614-87b2-11e5-8f80-fd32f6fc1b2e.png)

Notice: Undefined index: `/etc/apache2/sites-available/dev.domainname.net.conf` Size in /var/www/analogi/detail.php on line 577

**Comment by stskuen** [comment]
I have the same problem. Did you got a solution for that problem.

**Comment by thinksabin** [comment]
I did but I don't remember now. It has been long enough. I will update here if I find the solution again. If you do find the solution please don't to update this thread. :)

**Comment by krongi** [comment]
thinksabin, by chance can you just post the code from your detail.php? I'm getting an undefined index error ($phrase2) which is defined in earlier in the loop. Unsure what's going on but I'd like to see what you have if you can post it.

**Comment by thinksabin** [comment]
sorry, I don't have access to that machine anymore. If I do come across this issue and solution again, I will do post it.
