### ISSUE TITLE
ossec 2.9.1

### ISSUE THREAD

**Issue by derekneely** [ECSC/analogi#21]
We have ossec 2.9.1 up and running and data is being logged into the mysql db. However, analogi is reporting that the schema is incorrect. I don't have any agents up and running yet so not worried about that issue atm.

> Test 1 - Can PHP detect MySQL module? - yes
> Test 2 - Can PHP connect to your MySQL? - yes
> Test 3 - Does your database have correct schema? - no!
>        Fix - Import the MySQL schema that comes with OSSEC
> Test 4 - Is there any data in your database? - no!
>        Fix - Ensure agents are logging data.

**Comment by prasadpucsdian** [comment]
Hi Team,

I am facing this same problem.
Will you please help here.

**Comment by NunesGodinho** [comment]
The database schema was changed. The table data no longer exists.

**Comment by Aaron-Ming** [comment]
Hello, 我也遇到了这个问题，经过排查，我发现这个版本如果不更新，对ossec2.9.2版本不支持。

**Comment by karesmakro** [comment]
Hello there,
if you are interested, I'v adapted most of the code and it's running with PHP 7.0 and ossec 2.9.x
You have to know, that ossec 2.8.3 and 2.9.3 database scheme is not compatible. They have merged the row alert and data into own row called alert!
The Code is not completely fixed, but most of it is running. If I find the time, I'll fix it.

https://github.com/karesmakro/analogi-ecsc

**Comment by NunesGodinho** [comment]
I've forked this project into something new, in order to upgrade several stuff.
this is the final result:
https://github.com/NunesGodinho/OSSEC-WUI
